-- Instances

CREATE TABLE IF NOT EXISTS  instances (
    id varchar(255) PRIMARY KEY,
    delated_at TIMESTAMPTZ NOT NULL DEFAULT '0001-01-01 00:00:00+00',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE instances
    ADD COLUMN t1 TIMESTAMPTZ;

ALTER TABLE instances
    ADD COLUMN t2 TIMESTAMP;
